### PR TITLE
Particle filter bugfixes

### PR DESCRIPTION
**Pull request by yappel**
Fixed some bugs with the particle filter including:
Converting 2d vector to angle.
Actually taking range in consideration when searching for measurements.
Imu angle conversion.

### CODE REVIEW

**Comment by remcodevos** [comment]
TestWeightedAverage2 in CircularParticleControllerTest fails, as well as TestRealMarkerSensorData as mentioned in PR #81.

Code looks good, I cannot verify that it works with the hardware in Unity.

**Comment by yappel** [comment]
Fixed the failing test in weighted average. It expected 270 but it got -90 which are 2 equivalent angles.

**Comment by yappel** [comment]
The other test doesn't fail in this branch either on my machine as just like int #81

**Comment by lkrombeen** [comment]
Conflicts :melon:

**Comment by lkrombeen** [comment]
Merged developments, tests succeed and unity runs.

**Pull request merged**
