### PR TITLE
Changed distribution deviations after combining measurements

### LINKED ISSUE #19: Standard deviation and time in IMUSource.cs
The standard deviation and time is not right in multiple places in IMUSource.cs according to the comments in that class.

### PR DESCRIPTION
**Pull request by remcodevos**
Fixes #19. Velocity and displacement now have different and higher standard deviations than the acceleration std. The new std is computed following the rules of combining standard deviations and assuming a covariance of 0.

### CODE REVIEW

**Comment by lkrombeen** [comment]
You are having conflicts.

**Comment by remcodevos** [comment]
Fixed the conflicts.

**Comment by lkrombeen** [comment]
You got some violations

image

**Comment by lkrombeen** [comment]
Everything looks in order.

**Pull request merged**
