### PR TITLE
Improvement/missing imu tests

### PR DESCRIPTION
**Pull request by remcodevos**
Added missing tests for several classes. Also fixed a bug in IMU source displacement calculation calculating when there less than 2 velocity measurements.

### CODE REVIEW

**Comment by yappel** [comment]
Looks fine by me. Significantly improves the coverage in the IMU source class.

**Comment by lkrombeen** [comment]
GetLastVelocity is missing a test and so does NotifyVelocityFeedback.

**Comment by remcodevos** [comment]
GetLastVelocity missing branch cannot be covered: as always a starting velocity is set the case the branch that there is no velocity measurement never gets reached. That check remains though that future changes that might not have a starting velocity still return what is expected when a source has no measurement.

**Comment by remcodevos** [comment]
The failing test and and missing test for the velocity feedback have been added.

**Pull request merged**
