### PR TITLE
Added distribution types to the measurements

### PR DESCRIPTION
**Pull request by yappel**
The measurements now have a distribution type so the measurments can be processed more accurate.

### CODE REVIEW

**Comment by remcodevos** [comment]
Why exactly enums? Distribution types are not limited to the two currently implemented and using enums does not allow extendibility of other distribution types without explicitly adding them as an enum in the source and adding a clause for calculations at all the places where it is needed.

**Comment by lkrombeen** [comment]
Conflicts

**Comment by remcodevos** [comment]
Fixed the merge errors, all tests succeed.

**Comment by yappel** [comment]
The enums are removed and it now uses classes which improves the extendibility .

**Comment by lkrombeen** [comment]
I am getting build warnings:

image

Also getting stylecop warnings.

Tests are succeeding but missing a test for Uniform on CDF(2)

**Comment by lkrombeen** [comment]
Looks good, nice tool :hammer:

**Pull request merged**
